export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const GET_VIDEOGAME_DETAIL = "GET_VIDEOGAME_DETAIL";
export const GET_GENRES = "GET_GENRES";
export const GET_VIDEOGAMES_BY_NAME = "GET_VIDEOGAMES_BY_NAME"
export const SORT_VIDEOGAMES_BY = "SORT_VIDEOGAMES_BY"
export const SET_ORIGIN_FILTER = "SET_ORIGIN_FILTER"
export const SET_GENRE_FILTER = "SET_GENRE_FILTER"